name: Validation Deployment Check

on:
  schedule:
    - cron: '*/5 * * * *'  

    jobs:
  validation_check_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run validation deployment check
        id: validation
        run: |
           deployment_status=$(./check_deployment_status.sh)
          echo "Deployment status: $deployment_status"
          echo "::set-output name=status::$deployment_status"
          status="Pass"  # Example status, replace with actual logic

      - name: Report status
        if: steps.validation.outputs.status != ''  # Check if status variable is set
        run: |
          echo "Validation deployment status: ${{ steps.validation.outputs.status }}"

